language: python
sudo: false
branches:
only:
  - master
python:
  - 2.7

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes psutil
  - conda-env create -f install_gds_stack.yml
  - source activate gds

script: 
  - jupyter nbconvert --to markdown --execute --allow-errors check_gds_stack.ipynb --stdout

notifications:
    email:
        recipients:
            - daniel.arribas.bel@gmail.com
        on_success: always
        on_failure: always


